### ISSUE TITLE
请问这个是？ 会跑不动吧

### ISSUE THREAD

**Issue by mayyalove** [xjhqre/towhee-img-search#1]
extractFeatures.py 中 46行

img = image decode(path)

==========================

No definitions found using a precise lookupTry again with a search-based lookup. Learn more.

**Comment by xjhqre** [comment]
代码没上传完整，已修复

**Comment by xjhqre** [comment]
> extractFeatures.py 中 46行
> 
> img = image decode(path)
> 
> ==========================
> 
> No definitions found using a precise lookupTry again with a search-based lookup. Learn more.

代码没上传完整，已修复
